//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StudentManagementSystem.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome Message", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        internal static string EditModeTool {
            get {
                return ResourceManager.GetString("EditModeTool", resourceCulture);
            }
        }
        
        internal static string ReadModeTools {
            get {
                return ResourceManager.GetString("ReadModeTools", resourceCulture);
            }
        }
        
        internal static string BasicTools {
            get {
                return ResourceManager.GetString("BasicTools", resourceCulture);
            }
        }
        
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        internal static string SelectTool {
            get {
                return ResourceManager.GetString("SelectTool", resourceCulture);
            }
        }
        
        internal static string AgeSemicolon {
            get {
                return ResourceManager.GetString("AgeSemicolon", resourceCulture);
            }
        }
        
        internal static string SecondNameSemicolon {
            get {
                return ResourceManager.GetString("SecondNameSemicolon", resourceCulture);
            }
        }
        
        internal static string NameSemicolon {
            get {
                return ResourceManager.GetString("NameSemicolon", resourceCulture);
            }
        }
        
        internal static string HeadStudent {
            get {
                return ResourceManager.GetString("HeadStudent", resourceCulture);
            }
        }
        
        internal static string ChangeTypeTool {
            get {
                return ResourceManager.GetString("ChangeTypeTool", resourceCulture);
            }
        }
        
        internal static string AddRemoveTools {
            get {
                return ResourceManager.GetString("AddRemoveTools", resourceCulture);
            }
        }
        
        internal static string SelectFieldToEdit {
            get {
                return ResourceManager.GetString("SelectFieldToEdit", resourceCulture);
            }
        }
        
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        internal static string GroupIdToRemove {
            get {
                return ResourceManager.GetString("GroupIdToRemove", resourceCulture);
            }
        }
        
        internal static string GroupIDToOpen {
            get {
                return ResourceManager.GetString("GroupIDToOpen", resourceCulture);
            }
        }
        
        internal static string StudentIDToOpen {
            get {
                return ResourceManager.GetString("StudentIDToOpen", resourceCulture);
            }
        }
        
        internal static string PromoteDemoteFirstPart {
            get {
                return ResourceManager.GetString("PromoteDemoteFirstPart", resourceCulture);
            }
        }
        
        internal static string PromoteDemoteSecondPart {
            get {
                return ResourceManager.GetString("PromoteDemoteSecondPart", resourceCulture);
            }
        }
        
        internal static string Demote {
            get {
                return ResourceManager.GetString("Demote", resourceCulture);
            }
        }
        
        internal static string Promote {
            get {
                return ResourceManager.GetString("Promote", resourceCulture);
            }
        }
        
        internal static string StudentIDToChangeType {
            get {
                return ResourceManager.GetString("StudentIDToChangeType", resourceCulture);
            }
        }
        
        internal static string StudentIDToRemove {
            get {
                return ResourceManager.GetString("StudentIDToRemove", resourceCulture);
            }
        }
        
        internal static string NewStudent {
            get {
                return ResourceManager.GetString("NewString", resourceCulture);
            }
        }
    }
}
